language: node_js
node_js:
  - "10"
  - "6"
  - "8"
  - "9"
env:
  - AJV_VERSION=6
matrix:
  include:
    - env: AJV_VERSION=4
      node_js: "6"
    - env: AJV_VERSION=5
      node_js: "6"
    - env: AJV_VERSION=5
      node_js: "8"
before_script:
  - npm install --no-save ajv@$AJV_VERSION || true
cache: npm
